# Generated by Django 5.0.1 on 2024-01-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email_id',
            field=models.EmailField(max_length=120, unique=True),
        ),
    ]
